apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: capstone-blue
  name: blue-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: capstone-blue
  type: LoadBalancer
status:
  loadBalancer: {}
