apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: capstone-green
  name: green-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: capstone-green
  type: LoadBalancer
status:
  loadBalancer: {}
